<div class="modal fade" tabindex="-1" role="dialog" id="settingsModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="closeModal" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Settings</h4>
            </div>
            <div class="modal-body">
                <div class="btn-group btn-group-justified computerContent">
                    <div class="btn-group"><button class="btn btn-default settingsPreprocessing" type="button" data-toggle="collapse" data-target="#dataSetting" aria-expanded="false">Data processing</button></div>
                    <div class="btn-group"><button class="btn btn-default rawDatasets" type="button" data-toggle="collapse" data-target="#rawDatasets" aria-expanded="false">Datasets</button></div>
                 </div>

                <div class="btn-group btn-group-justified mobileContent">
                    <div class="btn-group"><button class="btn btn-default settingsPreprocessing" type="button" data-toggle="collapse" data-target="#dataSetting" aria-expanded="false">Processing</button></div>
                    <div class="btn-group"><button class="btn btn-default rawDatasets" type="button" data-toggle="collapse" data-target="#rawDatasets" aria-expanded="false">Datasets</button></div>
                </div>

                <div class="collapse" id="dataSetting">
                    <h4>Data Processing</h4>

                    The compute 5 pipeline from <a href="http://www.molgenis.org/wiki/ComputeStart">MOLGENIS</a> was used to process the data.
                    This pipeline contains several other features that were used to obtain results for BRAIN-sat.
                    Aligning was done with <a href="https://ccb.jhu.edu/software/hisat2/index.shtml">HISAT2</a>.
                    <a href="http://www.bioinformatics.babraham.ac.uk/index.html">FASTQC</a> was used to perform a quality check on obtained datasets.
                    Several preprocessing steps were performed with <a href="http://broadinstitute.github.io/picard/">Picard</a> and <a href="http://samtools.sourceforge.net/">Samtools</a>.
                    <a href="https://pypi.python.org/pypi/HTSeq">HTSeq</a> was used to obtain the counts for the datasets.
                    <br/>
                    <br/>
                    <h4>Analyses</h4>
                    The interactive analyses are done with R. The filtering of low expression genes is done with the use of <a href="https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-15-92">DAFS: a data-adaptive flag method</a>.
                    <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2796818/">EdgeR</a> is used to generate the differential gene expression lists and to obtain the quantitative gene information.
                    This information is displayed in an interactive vulcano scatterplot that is generated by <a href="https://plot.ly/">plotly</a>.
                    <br/>
                    <br/>

                    <h4>Visualization BRAIN-sat</h4>
                    The set-up of <a href="https://github.com/molgenis/molgenis">MOLGENIS</a> and several javascript packages where used in order to develop BRAIN-sat.
                    The sorting of the table content was done with the use of <a href="https://www.kryogenix.org/code/browser/sorttable/">sorttable</a>.
                    <a href="https://d3js.org/">D3js</a> was used in order to develop the interactive images of the QE data and the implementation of <a href="https://html2canvas.hertzen.com/">html2canvas</a> and <a href="https://github.com/MrRio/jsPDF">jsPDF</a> make sure that these images can be downloaded. <br/>
                    <a href="https://plot.ly/javascript/">Plotly</a> was used to generate the interactive images of the single cell data and the differential expression vulcano scatterplot of the bulk RNA data.
                    <br/>
                </div>

                <div class="collapse" id="rawDatasets">
                    <h4>Datasets</h4>
                        <table>
                            <colgroup>
                                <col width="25%">
                                <col width="10%">
                                <col width="10%">
                            </colgroup>
                            <tr>
                                <td>Butovsky et al. (2013)</td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/pubmed/25381879" target="_blank">Pubmed</a></td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52946" target="_blank">Data</a></td>
                            </tr>
                            <tr>
                                <td>Chiu et al. (2013)</td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/pubmed/23850290" target="_blank">Pubmed</a></td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE43366" target="_blank">Data</a></td>
                            </tr>
                            <tr>
                                <td>Galatro et al. (2013)</td>
                                <td><a href=https://www.ncbi.nlm.nih.gov/pubmed/28671693" target="_blank">Pubmed</a></td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE99074" target="_blank">Data</a></td>
                            </tr>
                            <tr>
                                <td>Gosselin et al. (2013)</td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/pubmed/25480297" target="_blank">Pubmed</a></td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE62826" target="_blank">Data</a></td>
                            </tr>
                            <tr>
                                <td>Hanamsagar et al. (2013)</td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/pubmed/28618077" target="_blank">Pubmed</a></td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE99622" target="_blank">Data</a></td>
                            </tr>
                            <tr>
                                <td>Matcovitch-Natan et al. (2013)</td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/pubmed/27338705" target="_blank">Pubmed</a></td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE79818" target="_blank">Data</a></td>
                            </tr>
                            <tr>
                                <td>Zhang et al. (2014)</td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/pubmed/25186741" target="_blank">Pubmed</a></td>
                                <td><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52564" target="_blank">Data</a></td>
                            </tr>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>
